<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Media_splash-close-container</name>
   <tag></tag>
   <elementGuidId>85b0b67b-821c-4273-a8d8-37a33b0bf5ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='splash-close-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#splash-close-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c5ad1a2b-c2c6-4037-b590-71ad54c54b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>splash-close-container</value>
      <webElementGuid>2f2aeb14-7438-493c-addf-5711468fa83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;splash-close-container&quot;)</value>
      <webElementGuid>7a6e12d2-5de3-47cf-8271-38d3b4efd833</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='splash-close-container']</value>
      <webElementGuid>83c679f7-1a70-477d-93a3-f215bae89328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Media'])[1]/following::div[4]</value>
      <webElementGuid>1ee1b8ce-4e27-4e7d-b39d-2295ea6b73a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='learn more'])[1]/following::div[10]</value>
      <webElementGuid>2fcc79c5-b78e-4318-a5d1-3b982cde8dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div</value>
      <webElementGuid>5a94a7b6-430e-455e-b774-af84e4665d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'splash-close-container']</value>
      <webElementGuid>8b58d26b-e443-4faa-afd4-454b4d9ab6e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
