<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_text_source</name>
   <tag></tag>
   <elementGuidId>d89ee08e-ace9-4268-acb1-7ecb0e0bc42c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder=&quot;Origin&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#content > input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3647142c-1b6d-452d-8218-83af523bbf58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ecfe143-5151-4896-b9fd-a05cf42810c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Origin</value>
      <webElementGuid>a3c10b8a-ac3a-41a4-9bb7-b6ec8b85deb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;by-route-container&quot;)/div[@class=&quot;sc-1fe02i9-0 hIfRqH&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;j9s0bi-1 ohdmw DropdownHeader sc-1qe11rp-0 jUOGgE&quot;]/div[@id=&quot;content&quot;]/input[1]</value>
      <webElementGuid>154de4fb-909b-4537-b999-8adec656a457</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>f377edac-a60f-4e4d-bbcc-dce125af03fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/input</value>
      <webElementGuid>77e2eb13-7673-4f60-a33c-92029d16bc3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/input</value>
      <webElementGuid>381f291a-4fc0-4562-9ca9-62603a03f78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Origin']</value>
      <webElementGuid>e51fd3dc-745b-4c1e-97db-e7120323c41b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
