<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas</name>
   <tag></tag>
   <elementGuidId>f5fb517e-77b6-47fd-9a9b-90623dca47b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='map-canvas']/div/div/div/canvas</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>cc6defc8-1c4d-4914-88ab-48c8db87d9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1920</value>
      <webElementGuid>375ddd9f-d244-442d-b1d9-a49bf2829dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>847</value>
      <webElementGuid>3f79f140-a0c8-4fa8-98e2-708be2ed9e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;map-canvas&quot;)/div[@class=&quot;ol-viewport&quot;]/div[@class=&quot;ol-unselectable ol-layers&quot;]/div[@class=&quot;ol-layer&quot;]/canvas[1]</value>
      <webElementGuid>b1adc5c0-c077-41cd-a4ac-52dfea748b35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='map-canvas']/div/div/div/canvas</value>
      <webElementGuid>44e38ac9-30ad-4efb-a9e3-936a484810cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>defc2a91-12e8-4a58-ba80-c417b2b5e9a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
